name: moneypal
description: A simple Android app enabling UPI-based payment for bills, recharges and peer-to-peer transactions, written in Flutter. Project submission for MAD Lab (Sem 6).

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  simple_animations: 1.3.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Gilroy Bold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf

    - family: Gilroy Bold Italic
      fonts:
        - asset: assets/fonts/Gilroy-BoldItalic.ttf

    - family: Gilroy Italic
      fonts:
        - asset: assets/fonts/Gilroy-Italic.ttf

    - family: Gilroy Medium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf

    - family: Gilroy Medium Italic
      fonts:
        - asset: assets/fonts/Gilroy-MediumItalic.ttf

    - family: Gilroy Regular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf